[platformio]
; Tell PlatformIO to pull in the real config that lives below
extra_configs = firmware/platformio.ini

; (Optional) choose a default environment so the usual toolbar
; buttons work without you having to pick one each time
default_envs = seeed_xiao_nrf52840_sense

src_dir = firmware/src
lib_dir = firmware/lib

[env]
; Make all environments look for source files in firmware/src