[env:seeed_xiao_nrf52840_sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
extra_scripts = pre:fix_link.py, post:apply_patches.py
framework = arduino
lib_deps = 
	adafruit/Adafruit BNO08x@^1.2.3
build_flags = 
  -Wl,-u,_printf_float
  -Wl,-wrap=realloc
lib_archive = no